### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by k1z1** [Jacxk/TimedFly#10]
./tfly help

in console:
[01:55:11] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tfly' in plugin TimedFly v3.0.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_05]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_05]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'tf' in plugin TimedFly v3.0.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at com.timedfly.commands.FlyCMD.onCommand(FlyCMD.java:57) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-8a983f9-e81edfc]
	... 14 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class mkremins.fanciful.FancyMessage
	at com.timedfly.commands.MainCommand.onCommand(MainCommand.java:51) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[Spigot.jar:git-Spigot-8a983f9-e81edfc]
	at com.timedfly.commands.FlyCMD.onCommand(FlyCMD.java:57) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-8a983f9-e81edfc]
	... 14 more

**Comment by Jacxk** [comment]
Try the [last version](https://www.spigotmc.org/resources/timedfly-3-mysql-support-1-8-1-12-2.48668/update?update=234634) of the plugin, and let me know if it keeps happening.

**Comment by k1z1** [comment]
thnx!
