### ISSUE TITLE
Error of update

### ISSUE THREAD

**Issue by HiImSunny** [Jacxk/TimedFly#32]
[13:24:37 ERROR]: Error occurred while enabling TimedFly v3.4.2 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method "com.timedfly.updater.Updater.<init>(Lcom/timedfly/TimedFly;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/timedfly/TimedFly, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/timedfly/updater/Updater, have different Class objects for the type com/timedfly/TimedFly used in the signature
        at com.timedfly.TimedFly.initializeClasses(TimedFly.java:117) ~[?:?]
        at com.timedfly.TimedFly.onEnable(TimedFly.java:65) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[%5b1.11.2%5d-%5bSkyRD%5d.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [%5b1.11.2%5d-%5bSkyRD%5d.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [%5b1.11.2%5d-%5bSkyRD%5d.jar:git-Spigot-3fb9445-6e3cec8]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) [PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) [PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) [PlugMan.jar:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [%5b1.11.2%5d-%5bSkyRD%5d.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [%5b1.11.2%5d-%5bSkyRD%5d.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [%5b1.11.2%5d-%5bSkyRD%5d.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636) [%5b1.11.2%5d-%5bSkyRD%5d.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437) [%5b1.11.2%5d-%5bSkyRD%5d.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400) [%5b1.11.2%5d-%5bSkyRD%5d.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [%5b1.11.2%5d-%5bSkyRD%5d.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [%5b1.11.2%5d-%5bSkyRD%5d.jar:git-Spigot-3fb9445-6e3cec8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by Jacxk** [comment]
This happens because the updater broke since the website I used is not available anymore. You have to disable the updater on the [config.yml](https://github.com/Jacxk/TimedFly/blob/stable/src/config.yml) file. If you don't have it yet just copy and paste the contents.

**Comment by Jacxk** [comment]
Check the new updates at https://github.com/Jacxk/TimedFly/releases
