### ISSUE TITLE
Console error 

### ISSUE THREAD

**Issue by HiImSunny** [Jacxk/TimedFly#48]
[18:45:29 WARN]: [TimedFly] Task #112375003 for TimedFly v4.4.1-BETA generated an exception
java.lang.NullPointerException: null
        at me.jackint0sh.timedfly.listeners.PlayerListener.lambda$handlePlayerQuery$4(PlayerListener.java:222) ~[?:?]
        at me.jackint0sh.timedfly.database.SQL.lambda$select$6(SQL.java:113) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

And on First Join

[17:30:12 WARN]: java.lang.Exception: Player not on database. Adding them...
[17:30:12 WARN]:        at me.jackint0sh.timedfly.database.SQL.lambda$select$5(SQL.java:102)
[17:30:12 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[17:30:12 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[17:30:12 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[17:30:12 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[17:30:12 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[17:30:12 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[17:30:12 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by Jacxk** [comment]
It always happens on first join because there's no user in the database, I believe I removed the error printing.
For the first error let me know if with the last update it happens also.
